// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VedasPortal.Data;

namespace VedasPortal.Migrations
{
    [DbContext(typeof(VedasDbContext))]
    [Migration("20220422075057_UsersTableAndRols2")]
    partial class UsersTableAndRols2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Anket.Anket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<string>("AnketSorusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("SecilenAnketMi")
                        .HasColumnType("bit");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamAlinanSure")
                        .HasColumnType("int");

                    b.Property<int>("ToplamKatilim")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Anket");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Anket.AnketSecenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_AnketId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamKatilim")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_AnketId");

                    b.ToTable("AnketSecenek");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Dosya.Dosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<string>("Boyutu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("DuzelticiFaaliyetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EgitimId")
                        .HasColumnType("int");

                    b.Property<int?>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<int?>("HaberDuyuruId")
                        .HasColumnType("int");

                    b.Property<int?>("IkUygulamaId")
                        .HasColumnType("int");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<int?>("KatilimciId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MevzuatId")
                        .HasColumnType("int");

                    b.Property<int?>("OneriId")
                        .HasColumnType("int");

                    b.Property<int?>("RehberId")
                        .HasColumnType("int");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uzanti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VideoId")
                        .HasColumnType("int");

                    b.Property<string>("Yolu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DuzelticiFaaliyetId");

                    b.HasIndex("EgitimId");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("HaberDuyuruId");

                    b.HasIndex("IkUygulamaId");

                    b.HasIndex("KatilimciId");

                    b.HasIndex("MevzuatId");

                    b.HasIndex("OneriId");

                    b.HasIndex("RehberId");

                    b.HasIndex("VideoId");

                    b.ToTable("Dosya");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.DuzelticiFaaliyet.DuzelticiFaaliyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BildirimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaaliyetGurupAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstekFaaliyetKonusu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KonuEtiketi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LokasyonBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DuzelticiFaaliyet");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Egitim.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<int>("Birimler")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Egitmen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gereksinim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KimlereUygun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonuBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sertifika")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.Property<long>("ToplamIzlenme")
                        .HasColumnType("bigint");

                    b.Property<long>("ToplamUzunluk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Egitim");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Egitim.OkulMezunBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EgitimDurumu")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MezuniyetTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OkulMezunBilgisi");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Etkinlik.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<bool>("AnasayfadaGoster")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KKategori")
                        .HasColumnType("int");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SliderdaGoster")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Etkinlik");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Etkinlik.Katilimci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<bool>("KatilisDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("KatilisNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId");

                    b.ToTable("Katilimci");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.HaberDuyuru.HaberDuyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<string>("AltBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AnasayfadaGoster")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SliderdaGoster")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HaberDuyuru");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.IKUygulama.IkUygulama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<int>("Birimler")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IkUygulama");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Kanban.GorevSecenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorevAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Oncellik")
                        .HasColumnType("int");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GorevSecenek");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Mevzuat.Mevzuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Birimler")
                        .HasColumnType("int");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Mevzuat");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Oneri.Oneri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<int>("Derece")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPosta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KabulDurum")
                        .HasColumnType("bit");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Odul")
                        .HasColumnType("int");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapanAdiSoyadı")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Oneri");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Rehber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokasyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TelefonNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Unvani")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rehber");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.Toplanti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<bool>("AnaSayfadaGoster")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BeklenenKatilimSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToplantiMerkeziId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToplantiTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VideoKonferansMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ToplantiMerkeziId");

                    b.ToTable("Toplanti");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Toplanti");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiMerkezi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Merkez");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiNotu.ToplantiNotu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("VarChar");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("Bit");

                    b.Property<string>("AltBaslik")
                        .IsRequired()
                        .HasColumnType("VarChar");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("VarChar");

                    b.Property<byte>("Birimler")
                        .HasColumnType("TinyInt");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("Date");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("VarChar");

                    b.Property<int?>("GetDosyaId")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("VarChar");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("VarChar");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("VarChar");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("Date");

                    b.Property<int?>("ToplantiMerkeziId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GetDosyaId");

                    b.HasIndex("ToplantiMerkeziId");

                    b.ToTable("ToplantiNotu");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiOdasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasite")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RezervDurumu")
                        .HasColumnType("bit");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToplantiId")
                        .HasColumnType("int");

                    b.Property<int?>("ToplantiMerkeziId")
                        .HasColumnType("int");

                    b.Property<bool>("VideoKonferansMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ToplantiId");

                    b.HasIndex("ToplantiMerkeziId");

                    b.ToTable("ToplantiOdasi");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.User.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AktifEdilsinMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SonGirisBilgisi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToplantiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToplantiId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Video.KursVeSertifika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GecerlilikSuresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SertifikaBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SertifikaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SertifikaUrlAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SertifikaVerilisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerenKurum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KursVeSertifika");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Video.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifPasif")
                        .HasColumnType("bit");

                    b.Property<string>("AltBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Birimler")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EgitimId")
                        .HasColumnType("int");

                    b.Property<int?>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<int?>("HaberDuyuruId")
                        .HasColumnType("int");

                    b.Property<bool>("IzlenmeDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("Uzunluk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EgitimId");

                    b.HasIndex("EtkinlikId");

                    b.HasIndex("HaberDuyuruId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Yorum.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuzenlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuzenleyenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnaylansınMı")
                        .HasColumnType("bit");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("Yorum");
                });

            modelBuilder.Entity("VedasPortal.Data.Toplanti.MailGonder", b =>
                {
                    b.HasBaseType("VedasPortal.Entities.Models.ToplantiTakvimi.Toplanti");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MailGonder");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Anket.AnketSecenek", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.Anket.Anket", "Anket")
                        .WithMany("AnketSecenek")
                        .HasForeignKey("Fk_AnketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anket");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Dosya.Dosya", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.DuzelticiFaaliyet.DuzelticiFaaliyet", "DuzelticiFaaliyet")
                        .WithMany("Dosya")
                        .HasForeignKey("DuzelticiFaaliyetId");

                    b.HasOne("VedasPortal.Entities.Models.Egitim.Egitim", "Egitim")
                        .WithMany("Dosya")
                        .HasForeignKey("EgitimId");

                    b.HasOne("VedasPortal.Entities.Models.Etkinlik.Etkinlik", "Etkinlik")
                        .WithMany("Dosya")
                        .HasForeignKey("EtkinlikId");

                    b.HasOne("VedasPortal.Entities.Models.HaberDuyuru.HaberDuyuru", "HaberDuyuru")
                        .WithMany("Dosya")
                        .HasForeignKey("HaberDuyuruId");

                    b.HasOne("VedasPortal.Entities.Models.IKUygulama.IkUygulama", "IkUygulama")
                        .WithMany("Dosya")
                        .HasForeignKey("IkUygulamaId");

                    b.HasOne("VedasPortal.Entities.Models.Etkinlik.Katilimci", "Katilimci")
                        .WithMany("Dosya")
                        .HasForeignKey("KatilimciId");

                    b.HasOne("VedasPortal.Entities.Models.Mevzuat.Mevzuat", "Mevzuat")
                        .WithMany("Dosya")
                        .HasForeignKey("MevzuatId");

                    b.HasOne("VedasPortal.Entities.Models.Oneri.Oneri", "Oneri")
                        .WithMany("Dosya")
                        .HasForeignKey("OneriId");

                    b.HasOne("VedasPortal.Entities.Models.Rehber", "Rehber")
                        .WithMany("Dosya")
                        .HasForeignKey("RehberId");

                    b.HasOne("VedasPortal.Entities.Models.Video.Video", "Video")
                        .WithMany("Dosya")
                        .HasForeignKey("VideoId");

                    b.Navigation("DuzelticiFaaliyet");

                    b.Navigation("Egitim");

                    b.Navigation("Etkinlik");

                    b.Navigation("HaberDuyuru");

                    b.Navigation("IkUygulama");

                    b.Navigation("Katilimci");

                    b.Navigation("Mevzuat");

                    b.Navigation("Oneri");

                    b.Navigation("Rehber");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Etkinlik.Katilimci", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.Etkinlik.Etkinlik", "Etkinlik")
                        .WithMany("Katilimci")
                        .HasForeignKey("EtkinlikId");

                    b.Navigation("Etkinlik");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.Toplanti", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiMerkezi", "ToplantiMerkezi")
                        .WithMany()
                        .HasForeignKey("ToplantiMerkeziId");

                    b.Navigation("ToplantiMerkezi");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiNotu.ToplantiNotu", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.Dosya.Dosya", "GetDosya")
                        .WithMany()
                        .HasForeignKey("GetDosyaId");

                    b.HasOne("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiMerkezi", "ToplantiMerkezi")
                        .WithMany()
                        .HasForeignKey("ToplantiMerkeziId");

                    b.Navigation("GetDosya");

                    b.Navigation("ToplantiMerkezi");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiOdasi", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.ToplantiTakvimi.Toplanti", "Toplanti")
                        .WithMany("ToplantiOdasi")
                        .HasForeignKey("ToplantiId");

                    b.HasOne("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiMerkezi", "ToplantiMerkezi")
                        .WithMany("ToplantiOdasi")
                        .HasForeignKey("ToplantiMerkeziId");

                    b.Navigation("Toplanti");

                    b.Navigation("ToplantiMerkezi");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.User.Kullanici", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.ToplantiTakvimi.Toplanti", "Toplanti")
                        .WithMany("Kullanici")
                        .HasForeignKey("ToplantiId");

                    b.Navigation("Toplanti");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Video.Video", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.Egitim.Egitim", "Egitim")
                        .WithMany("Video")
                        .HasForeignKey("EgitimId");

                    b.HasOne("VedasPortal.Entities.Models.Etkinlik.Etkinlik", "Etkinlik")
                        .WithMany()
                        .HasForeignKey("EtkinlikId");

                    b.HasOne("VedasPortal.Entities.Models.HaberDuyuru.HaberDuyuru", "HaberDuyuru")
                        .WithMany("Video")
                        .HasForeignKey("HaberDuyuruId");

                    b.Navigation("Egitim");

                    b.Navigation("Etkinlik");

                    b.Navigation("HaberDuyuru");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Yorum.Yorum", b =>
                {
                    b.HasOne("VedasPortal.Entities.Models.Video.Video", "Video")
                        .WithMany("VideoYorum")
                        .HasForeignKey("VideoId");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Anket.Anket", b =>
                {
                    b.Navigation("AnketSecenek");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.DuzelticiFaaliyet.DuzelticiFaaliyet", b =>
                {
                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Egitim.Egitim", b =>
                {
                    b.Navigation("Dosya");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Etkinlik.Etkinlik", b =>
                {
                    b.Navigation("Dosya");

                    b.Navigation("Katilimci");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Etkinlik.Katilimci", b =>
                {
                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.HaberDuyuru.HaberDuyuru", b =>
                {
                    b.Navigation("Dosya");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.IKUygulama.IkUygulama", b =>
                {
                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Mevzuat.Mevzuat", b =>
                {
                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Oneri.Oneri", b =>
                {
                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Rehber", b =>
                {
                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.Toplanti", b =>
                {
                    b.Navigation("Kullanici");

                    b.Navigation("ToplantiOdasi");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.ToplantiTakvimi.ToplantiMerkezi", b =>
                {
                    b.Navigation("ToplantiOdasi");
                });

            modelBuilder.Entity("VedasPortal.Entities.Models.Video.Video", b =>
                {
                    b.Navigation("Dosya");

                    b.Navigation("VideoYorum");
                });
#pragma warning restore 612, 618
        }
    }
}
